CC=gcc
CFLAGS=-std=c11 -Wall -Werror -Wextra -pedantic -g

ex_1_to_4: ex_1_to_4.c
	$(CC) -o ex_1_to_4 ex_1_to_4.c $(CFLAGS)

hexabyte: hexabyte.c
	$(CC) -o hexabyte hexabyte.c $(CFLAGS)

int2ascii: int2ascii.c
	$(CC) -o int2ascii int2ascii.c $(CFLAGS)

ascii2int: ascii2int.c
	$(CC) -o ascii2int ascii2int.c $(CFLAGS)