CC=gcc
CFLAGS=-std=c11 -Wall -Werror -Wextra -pedantic -g

hello_world: hello_world.c
	$(CC) -o hello_world hello_world.c $(CFLAGS)

repeatme: repeatme.c
	$(CC) -o repeatme repeatme.c $(CFLAGS)

noAs: noAs.c
	$(CC) -o noAs noAs.c $(CFLAGS)

roll: roll.c
	  $(CC) -o roll roll.c $(CFLAGS)