CC=gcc
CFLAGS=-std=c11 -Wall -Werror -Wextra -pedantic -g

ex_2_2: ex_2_2.c
	$(CC) -o ex_2_2 ex_2_2.c $(CFLAGS)

ex_2_4: ex_2_4.c
	$(CC) -o ex_2_4 ex_2_4.c $(CFLAGS)

ex_2_24_2: ex_2_24_2.c
	$(CC) -o ex_2_24_2 ex_2_24_2.c $(CFLAGS)

ex_2_24_4: ex_2_24_4.c
	$(CC) -o ex_2_24_4 ex_2_24_4.c $(CFLAGS)